### ISSUE TITLE
Is it possible to add the event parameters to the featureout event?

### ISSUE THREAD

**Issue by danielbeeke** [Vizzuality/cartodb-leaflet#19]
Is it possible to add the event parameters to the featureout event?

I have countries on a map and need to be able to find the layer again by a variable.

http://pastebin.com/79hZGZ6K

**Comment by xavijam** [comment]
Hi!
For the moment no, the featureOut event only fires when you are out of all feature points of the layer. We are pushing to improve this in the next version and provide "out events" every time you "hover out" a point.

Cheers!

**Comment by danielbeeke** [comment]
Ok, I have fixed this by creating a vector which has a marker mouseout function,
