### ISSUE TITLE
examples seem to be broken

### ISSUE THREAD

**Issue by andrewxhill** [Vizzuality/cartodb-leaflet#22]
hover-line and hover-point are failing. will try to debug better when I have a second

**Comment by xavijam** [comment]
It's working for me.

http://vizzuality.github.com/cartodb-leaflet/examples/hover-polygon.html

Could you try again buddy?

**Comment by andrewxhill** [comment]
Just checked, working fine. Cheers!

**Comment by pdxmele** [comment]
Hover-point still doesn't seem to be working for me (hosted http://vizzuality.github.com/cartodb-leaflet/examples/hover-point.html or downloaded), and I'd really like to work off of it for a project. Could you have another look, please?

Also, I thought you would want to know that the link to the examples on http://vizzuality.github.com/cartodb-leaflet/ sends you to a 404: http://vizzuality.github.com/cartodb-leaflet/examples/
