### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by rpsirois** [Vizzuality/cartodb-leaflet#23]
It would be nice to have access to the Leaflet layer object. The CartoDB layer object seems to hijack attribution.

**Comment by xavijam** [comment]
Hi rpsirois!

We've just updated the library and now you set the attribution test as you want. Just add the attribution parameter in the initialize of the CartoDB leaflet layer. Also, if you want to edit it in execution time, you could use setAttribution function or change with the generic setOptions function. Hope it helps.

Thanks for your feedback!

**Comment by rpsirois** [comment]
@xavijam Awesome thanks! Works great!
